using KantorLr1.ViewModels.Base;
using System;
using System.Collections.Generic;
using System.Text;

namespace KantorLr1.ViewModels
{
	public class AutoGenerateDataViewModel : BaseViewModel
	{
		private string title = "Hello";
		public string Title { get => title; set => Set(ref title, value); }

		public AutoGenerateDataViewModel()
		{
			Title = "Hello";
		}
	}
}
